name: Mi Primer Pipeline

on: [push]

jobs:
  preparar-entorno:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Instalar Node.js en la nube
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias automáticamente
        run: npm ci